FROM python:3.9-slim
COPY . /app
WORKDIR /app
CMD ["python", "first.py"]

# FROM grabs a base Python image (like starting with a pre-built house).
# COPY adds your script.
# CMD runs it when the container starts.